const { defineConfig } = require("eslint/config");
const expoConfig = require("eslint-config-expo/flat");
const eslintPluginPrettierRecommended = require("eslint-plugin-prettier/recommended");

module.exports = defineConfig([
  expoConfig,
  eslintPluginPrettierRecommended,
  {
    // `expo lint . --fix` walks the whole tree and rewrites what it finds, so
    // anything here that isn't this repo's own source gets edited behind your
    // back. Agent worktrees are the one that bites: linting from the root used
    // to reformat files inside a parallel checkout, dirtying it and blocking
    // `git worktree remove`. Jest already skips them via
    // `testPathIgnorePatterns` in package.json — keep the two lists in step.
    //
    // `expo-env.d.ts` is generated by `expo start`, which writes it without a
    // trailing newline; `--fix` adding one only for the next start to remove
    // it again was a permanent lint error nobody could keep fixed.
    ignores: ["dist/*", ".claude/worktrees/**", "coverage/**", "expo-env.d.ts"],
  },
  {
    // Edge Functions run on Deno, which resolves `npm:` specifiers and `.ts`
    // paths that Node's resolver does not know. Everything else still applies.
    files: ["supabase/functions/**"],
    rules: { "import/no-unresolved": "off" },
  },
  {
    // `jest.mock` factories are hoisted above every import, so `require` is the
    // only way to reach a module from inside one — and the same goes for
    // reading back a mock a factory built (`__router`, the push helpers).
    files: ["__tests__/**", "jest.setup.js"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
]);
